<a href="https://colab.research.google.com/github/wenh08/Python_projects-/blob/main/EPADataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from numpy.random import randn
np.random.seed(123)

In [ ]:
#what is a matrix? a mitrix is a regtangular arrangment of values organized into rows and clomuns

In [3]:
 df = pd.DataFrame(randn(5,4),['A','B','C','D','E',],['W','X', 'Y','Z'])
 # Dataframes are made up of mulitiple lists (or series)
df['W'].dtype
 # if we wanted select mulitiple columns from our dataframe, we pass a list of column names
 # df[['W', 'X']]
# Adding new columns in dataframes
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A -1.085631  0.997345  0.282978 -1.506295 -0.802652
B -0.578600  1.651437 -2.426679 -0.428913 -3.005279
C  1.265936 -0.866740 -0.678886 -0.094709  0.587050
D  1.491390 -0.638902 -0.443982 -0.434351  1.047408
E  2.205930  2.186786  1.004054  0.386186  3.209984

In [ ]:
# Removing columns in dataframes


#Always mind the syntax
# df.drop('new', axis =1, inplace = True )
# why are these paramenters necessary?
#In python, axis = 1 refers to column identification and axis = 0 refers to row identification
# inplace = True tells python to modify the existing dataframe (save vs. save as)

In [7]:
# Creating subsets of original dataframes
df2 = df[['W', 'X']]
# our new dataframe will now only have two columns

In [8]:
# Droping rows in dataframs

#what do you notice about the syntax below?

df.drop('E', axis = 0)

          W         X         Y         Z       new
A -0.772709  0.794863  0.314272 -1.326265 -0.458437
B  1.417299  0.807237  0.045490 -0.233092  1.462789
C -1.198301  0.199524  0.468439 -0.831155 -0.729862
D  1.162204 -1.097203 -2.123100  1.039727 -0.960896

In [4]:
# Selecting rows in dataframes
# many ways to do this, but the most common is loc and iloc

df.loc['C']
#Row label in string format

W      1.265936
X     -0.866740
Y     -0.678886
Z     -0.094709
new    0.587050
Name: C, dtype: float64

In [5]:
df.iloc[2]
#index

W      1.265936
X     -0.866740
Y     -0.678886
Z     -0.094709
new    0.587050
Name: C, dtype: float64

In [ ]:
# Renaming columns in dataframes
# messy data sometimes means messy columns
# renaming columns, information gets fed in as a dictinary {} <- dictinary

#df = df.rename(columns= { 'Unamed: 0': 'newName1', 'oldName2': 'newName2'})

# Oe rename the existing DataFrame (rather than creating a copy)

#df.rename(columns={'oldName1': 'newName1', 'oldName2': 'newName2'}, inplace=True)

# example from my TLC project

#df2 = df_rides.rename(columns={'base_passenger_fare': 'fare'})

# The dictionary:

# {'base_passenger_fare': 'fare'}

#'base_passenger_fare' : 'fare'
 #       OLD               NEW
# Your original df_rides stays unchanged, while df2 gets the new column name.

# Option 2 — Change df_rides itself

# df_rides.rename(columns=
#{'base_passenger_fare': 'fare'}, inplace = True
#)

In [8]:
EPA_df = pd.read_csv("https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/refs/heads/master/mtcars.csv")

In [9]:
EPA_df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [11]:
EPA_df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [12]:
# Clean the dataset by naming the missing column name

EPA_df.rename(columns= {'Unnamed: 0': 'vehicle'}, inplace=True)

In [14]:
# create a new dataframe that consists of a subset of the original
#columns (only mpg, hp, wt, and cyl)
# we need a list because we are selecting mulitiple columns

EDA_subset = EPA_df[['mpg', 'hp', 'wt', 'cyl']]

EDA_subset.head()
#checking to make sure the new dataframe exists with only these columns

    mpg   hp     wt  cyl
0  21.0  110  2.620    6
1  21.0  110  2.875    6
2  22.8   93  2.320    4
3  21.4  110  3.215    6
4  18.7  175  3.440    8

In [35]:
EDA_subset.rename(columns = {'cyl': 'cylinders',
                             'mpg': 'Miles per gallon', 'wt':'weight', 'hp': 'horse power'},
                   inplace = True)

/tmp/ipykernel_1280/1913626262.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EDA_subset.rename(columns = {'cyl': 'cylinders',

In [36]:
EDA_subset.head()

   Miles per gallon  horse power  weight  cylinders
0              21.0          110   2.620          6
1              21.0          110   2.875          6
2              22.8           93   2.320          4
3              21.4          110   3.215          6
4              18.7          175   3.440          8

In [37]:
#summary statistics for those columns (average mpg)

EDA_subset.describe()

       Miles per gallon  horse power     weight  cylinders
count         32.000000    32.000000  32.000000  32.000000
mean          20.090625   146.687500   3.217250   6.187500
std            6.026948    68.562868   0.978457   1.785922
min           10.400000    52.000000   1.513000   4.000000
25%           15.425000    96.500000   2.581250   4.000000
50%           19.200000   123.000000   3.325000   6.000000
75%           22.800000   180.000000   3.610000   8.000000
max           33.900000   335.000000   5.424000   8.000000

In [38]:
# summary statistics for those columns (average mpg)
print(EDA_subset['Miles per gallon'].mean())

20.090625000000003

In [39]:
#filter your data and find summary statistics for only one type of vehicle

EDA_subset['cylinders']

0     6
1     6
2     4
3     6
4     8
5     6
6     8
7     4
8     4
9     6
10    6
11    8
12    8
13    8
14    8
15    8
16    8
17    4
18    4
19    4
20    4
21    8
22    8
23    8
24    8
25    4
26    4
27    4
28    8
29    6
30    8
31    4
Name: cylinders, dtype: int64

In [43]:
four_cylinders = EDA_subset[EDA_subset['cylinders'] == 4]

four_cylinders.describe()

# I filtered the dataset to analyze only 4-cylinder vehicles. There are 11 4-cylinder vehicles in the dataset. They have an average MPG of 26.66, average horsepower of 82.64, and average weight of 2.29

       Miles per gallon  horse power     weight  cylinders
count         11.000000    11.000000  11.000000       11.0
mean          26.663636    82.636364   2.285727        4.0
std            4.509828    20.934530   0.569564        0.0
min           21.400000    52.000000   1.513000        4.0
25%           22.800000    65.500000   1.885000        4.0
50%           26.000000    91.000000   2.200000        4.0
75%           30.400000    96.000000   2.622500        4.0
max           33.900000   113.000000   3.190000        4.0